version: '3.8'
services:
  bind9:
    image: internetsystemsconsortium/bind9:9.18
    container_name: bind9
    ports:
      - "8053:53/tcp"
      - "8053:53/udp"
    volumes:
      - ./named.conf.options:/etc/bind/named.conf.options
      - ./zones:/etc/bind/zones
      - ./logs:/var/log/bind
    restart: unless-stopped
